version: "2.15.1"

services:  
  ollama:
    volumes:
      - /home/alex/.ollama/:/root/.ollama/
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:11434:11434
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    networks:
      - llm_docker_net
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:3000:8080
    depends_on:
      - ollama
    volumes:
      - /home/alex/.ollama_openwebui:/app/backend/data
    container_name: open-webui
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    restart: unless-stopped
    networks:
      - llm_docker_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  llm_docker_net:
